### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by KCM30114**
modified contents of file

### CODE REVIEW

**Comment by KCM30114** [comment]
would like for you to consider my fixes to the write ups.  Please look at the changes and tell me what you think.

**Review by mcm30114 — APPROVED** [review]
Edits look good .. approving PR

**Comment by mcm30114** [comment]
@KCM30114  -- Good job.  Your edits are now pulled into the Master Branch .. you may want to check your master to see if it synched back to your repo.  

If it did. I would then delete the branch that you created for the edit, create another branch from your MASTER and continue editing from there ..

**Comment by KCM30114** [comment]
It did not automatically sync, so I have gone ahead and deleted the old fork and made a new fork to at least still be able to work on the current version

**Pull request merged**
